=== 18xx-maker/18xx-maker/src/data/schemas/companies.schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "$id": "https://18xx.kelsin.net/schemas/companies.schema.json",

  "type": "object",
  "properties": {
    "yellow": { "$ref": "theme.schema.json#/definitions/color" },
    "orange": { "$ref": "theme.schema.json#/definitions/color" },
    "red": { "$ref": "theme.schema.json#/definitions/color" },
    "pink": { "$ref": "theme.schema.json#/definitions/color" },
    "white": { "$ref": "theme.schema.json#/definitions/color" },
    "gold": { "$ref": "theme.schema.json#/definitions/color" },
    "black": { "$ref": "theme.schema.json#/definitions/color" },
    "gray": { "$ref": "theme.schema.json#/definitions/color" },
    "blue": { "$ref": "theme.schema.json#/definitions/color" },
    "navyBlue": { "$ref": "theme.schema.json#/definitions/color" },
    "cyan": { "$ref": "theme.schema.json#/definitions/color" },
    "green": { "$ref": "theme.schema.json#/definitions/color" },
    "lime": { "$ref": "theme.schema.json#/definitions/color" },
    "turquoise": { "$ref": "theme.schema.json#/definitions/color" },
    "purple": { "$ref": "theme.schema.json#/definitions/color" },
    "lavender": { "$ref": "theme.schema.json#/definitions/color" },
    "brown": { "$ref": "theme.schema.json#/definitions/color" },
    "tan": { "$ref": "theme.schema.json#/definitions/color" },
    "natural": { "$ref": "theme.schema.json#/definitions/color" }
  },
  "additionalProperties": false
}

=== 18xx-maker/18xx-maker/src/data/themes/companies/broggles.json
{
  "black": "#565655",
  "blue": "#5c92a5",
  "brown": "#a27918",
  "cyan": "#00c9ff",
  "gray": "#848484",
  "green": "#417e2e",
  "lavender": "#a04d78",
  "lime": "#6e9268",
  "natural": "#ccc6a0",
  "orange": "#f6a012",
  "pink": "#ec676a",
  "purple": "#60344a",
  "red": "#861108",
  "tan": "#de9659",
  "turquoise": "#84967f",
  "white": "#fff",
  "yellow": "#e4d057"
}
