=== 18xx-maker/18xx-maker/src/schemas/game.schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "$id": "https://18xx-maker.com/schemas/game.schema.json",

  "definitions": {
    "numberOrSlash": {
      "oneOf": [
        { "type": "number", "minimum": 1 },
        {
          "type": "string",
          "pattern": "^[0-9]+ ?/ ?[0-9]+( ?/ ?[0-9]+)*$"
        },
        {
          "type": "string",
          "pattern": "^∞$"
        }
      ]
    },
    "bank": {
      "oneOf": [
        { "type": "number", "minimum": 1 },
        {
          "type": "string",
          "pattern": "^∞$"
        }
      ]
    },
    "capital": {
      "oneOf": [{ "type": "number", "minimum": 0 }, { "type": "string" }]
    },
    "certLimit": { "$ref": "#/definitions/numberOrSlash" },
    "link": {
      "type": "string",
      "pattern": "(mailto|https?):.*"
    },
    "map": {
      "type": "object",
      "properties": {
        "name": { "type": "string" },
        "copy": { "type": "integer", "minimum": 0 },
        "title": { "type": "boolean", "enum": [false] },
        "remove": {
          "type": "array",
          "items": {
            "type": "string",
            "pattern": "^[A-Z]+[0-9]+$"
          }
        },
        "hexes": {
          "type": "array",
          "items": { "$ref": "tiles.schema.json#/definitions/hex" }
        },
        "roundTracker": {
          "type": "object",
          "properties": {
            "x": { "type": "number" },
            "y": { "type": "number" },
            "rotation": {
              "type": "number",
              "exclusiveMinimum": -360,
              "exclusiveMaximum": 360
            },
            "type": {
              "type": "string",
              "enum": ["row", "row-reverse", "col", "col-reverse", "round"]
            }
          },
          "additionalProperties": false
        },
        "players": {
          "type": "object",
          "properties": {
            "x": { "type": "number" },
            "y": { "type": "number" },
            "cellWidth": { "type": "number", "exclusiveMinimum": 0 }
          },
          "additionalProperties": false
        },
        "borderTexts": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "cost": { "type": "number" },
              "circle": { "type": "number" },
              "color": { "type": "string" },
              "bgColor": { "type": "string" },
              "coord": {
                "type": "string",
                "pattern": "^[A-Z]+[0-9]+(s[1-6])|(p[1-6])|(a[0-9]+p[0-9]+)|(x[0-9]+y[0-9]+)"
              }
            }
          }
        },
        "borders": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "color": { "type": "string" },
              "coords": {
                "type": "array",
                "items": {
                  "type": "string",
                  "pattern": "^[A-Z]+[0-9]+(s[1-6])|(p[1-6])|(a[0-9]+p[0-9]+)|(x[0-9]+y[0-9]+)"
                }
              }
            }
          }
        }
      },
      "required": ["hexes"],
      "additionalProperties": false
    },
    "trainItem": {
      "oneOf": [
        { "type": "string" },
        {
          "type": "object",
          "properties": {
            "on": { "type": "string" },
            "index": { "type": "integer", "minimum": 2 }
          }
        }
      ]
    },
    "trainEvent": {
      "oneOf": [
        { "$ref": "#/definitions/trainItem" },
        { "type": "array", "items": { "$ref": "#/definitions/trainItem" } }
      ]
    },
    "shares": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "quantity": { "type": "number", "minimum": 1 },
          "label": { "type": "string" },
          "cost": { "type": "number", "minimum": 0 },
          "percent": { "$ref": "#/definitions/numberOrSlash" },
          "revenue": { "$ref": "#/definitions/numberOrSlash" },
          "shares": { "$ref": "#/definitions/numberOrSlash" },
          "variant": { "type": "string" }
        },
        "required": ["quantity"]
      }
    },
    "tokens": {
      "type": "array",
      "items": {
        "oneOf": [
          { "type": "string" },
          { "type": "number" },
          { "$ref": "#/definitions/token" }
        ]
      }
    },
    "token": {
      "type": "object"
    }
  },

  "type": "object",
  "properties": {
    "info": {
      "type": "object",
      "properties": {
        "title": { "type": "string" },
        "subtitle": { "type": "string" },
        "designer": { "type": "string" },
        "background": { "type": "string" },
        "notes": { "type": "string" },
        "publisher": { "type": "string" },
        "extraTotalHeight": { "type": "number", "minimum": 1 },
        "extraTotalWidth": { "type": "number", "minimum": 1 },
        "titleX": { "type": "number" },
        "titleY": { "type": "number" },
        "titleRotate": {
          "type": "number",
          "minimum": -360,
          "maximum": 360
        },
        "titleSize": { "type": "number" },
        "subtitleSize": { "type": "number" },
        "designerSize": { "type": "number" },
        "titleFontFamily": { "type": "string" },
        "subtitleFontFamily": { "type": "string" },
        "designerFontFamily": { "type": "string" },
        "orientation": {
          "type": "string",
          "enum": ["horizontal", "vertical"]
        },
        "capitalization": {
          "type": "string",
          "description": "Full cap is the default and doesn't need to be specified.",
          "enum": ["incremental"]
        },
        "mustSellInBlocks": { "type": "boolean", "enum": [true] },
        "marketTokens": { "type": "integer", "minimum": 0 },
        "extraStationTokens": { "type": "integer", "minimum": 1 },
        "mustSellInBlocks": { "type": "boolean" },
        "capitalization": {
          "type": "string",
          "enum": ["full", "incremental"]
        },
        "currency": {
          "description": "The currency format string must contain a # character",
          "type": "string",
          "pattern": "^(.*)#(.*)$"
        }
      },
      "required": ["title"],
      "additionalProperties": false
    },
    "colors": {
      "type": "object"
    },
    "links": {
      "type": "object",
      "properties": {
        "bgg": { "$ref": "#/definitions/link" },
        "license": { "$ref": "#/definitions/link" },
        "purchase": { "$ref": "#/definitions/link" },
        "rules": { "$ref": "#/definitions/link" }
      },
      "additionalProperties": false
    },
    "bank": { "$ref": "#/definitions/bank" },
    "capital": { "$ref": "#/definitions/capital" },
    "certLimit": { "$ref": "#/definitions/certLimit" },
    "floatPercent": { "type": "number", "minimum": 0, "maximum": 100 },
    "tokenTypes": {
      "type": "object",
      "additionalProperties": { "$ref": "#/definitions/tokens" }
    },
    "shareTypes": {
      "type": "object",
      "additionalProperties": { "$ref": "#/definitions/shares" }
    },
    "companies": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["name", "abbrev"],
        "properties": {
          "name": { "type": "string" },
          "variant": { "type": "string" },
          "shares": {
            "oneOf": [{ "$ref": "#/definitions/shares" }, { "type": "string" }]
          },
          "tokens": {
            "oneOf": [{ "$ref": "#/definitions/tokens" }, { "type": "string" }]
          }
        }
      }
    },
    "ipo": {
      "oneOf": [
        { "type": "boolean" },
        { "type": "array", "items": { "type": "string" } }
      ]
    },
    "map": {
      "oneOf": [
        { "$ref": "#/definitions/map" },
        { "type": "array", "items": { "$ref": "#/definitions/map" } }
      ]
    },
    "phases": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "minor": { "type": "boolean" },
          "company": { "type": "string" },
          "train": {
            "oneOf": [
              { "type": "array", "items": { "type": "string" } },
              { "type": "string" }
            ]
          },
          "limit": {
            "oneOf": [
              { "type": "integer", "minimum": 1 },
              {
                "type": "string",
                "pattern": "^∞$"
              }
            ]
          },
          "rounds": { "type": "integer", "minimum": 1 },
          "tiles": { "type": "string" },
          "on": { "$ref": "#/definitions/trainEvent" },
          "notes": {
            "oneOf": [
              { "type": "string" },
              {
                "type": "array",
                "items": { "type": "string" }
              }
            ]
          },
          "buy_companies": { "type": "boolean" },
          "events": {
            "type": "object",
            "additionalProperties": {
              "type": "boolean"
            }
          }
        },
        "required": ["name", "limit", "tiles"],
        "additionalProperties": false
      }
    },
    "players": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "bank": { "$ref": "#/definitions/bank" },
          "capital": { "$ref": "#/definitions/capital" },
          "certLimit": { "$ref": "#/definitions/certLimit" },
          "number": { "type": "number", "minimum": 1 }
        },
        "required": ["number"]
      }
    },
    "pools": {},
    "privates": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "note": { "type": "string" },
          "minPlayers": { "type": "integer", "minimum": 1 },
          "maxPlayers": { "type": "integer", "minimum": 1 },
          "description": { "type": "string" },
          "hex": { "type": "string" },
          "token": { "$ref": "#/definitions/token" },
          "company": { "type": "string" },
          "image": { "type": "string" },
          "icon": { "type": "string" },
          "iconColor": { "type": "string" },
          "tile": { "type": "string" },
          "id": { "type": "string" },
          "idBackgroundColor": { "type": "string" },
          "variant": { "type": "string" },
          "sym": { "type": "string" },
          "abilities": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "type": { "type": "string" }
              }
            }
          },
          "bid": { "type": "number", "minimum": 0 },
          "price": { "type": "number", "minimum": 0 },
          "debt": { "type": "number", "minimum": 0 },
          "revenue": {
            "oneOf": [
              { "type": "number", "minimum": 0 },
              {
                "type": "array",
                "items": { "type": "number", "minimum": 0 }
              },
              {
                "type": "string",
                "pattern": "^.?.?[0-9].?%? ?/ ?.?.?[0-9].?%?$"
              }
            ]
          }
        },
        "required": ["name"],
        "additionalProperties": false
      }
    },
    "rounds": {},
    "stock": {},
    "tiles": {
      "type": "object",
      "additionalProperties": {
        "oneOf": [
          {
            "type": "integer",
            "minimum": 1
          },
          {
            "$ref": "tiles.schema.json#/definitions/hex"
          }
        ]
      }
    },
    "tokens": {},
    "turns": {},
    "trains": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "price": { "type": "integer", "minimum": 0 },
          "color": { "type": "string" },
          "image": {
            "type": "string"
          },
          "phase": { "type": "boolean" },
          "quantity": {
            "oneOf": [
              { "type": "integer", "minimum": 1 },
              { "type": "string", "enum": ["∞"] }
            ]
          },
          "print": { "type": "integer", "minimum": 0 },
          "discount": { "type": "object" },
          "description": { "type": "string" },
          "available": { "type": "string" },
          "variant": { "type": "string" },
          "rust": { "$ref": "#/definitions/trainEvent" },
          "phased": { "$ref": "#/definitions/trainEvent" },
          "obsolete": { "$ref": "#/definitions/trainEvent" },
          "permanent": { "type": "boolean" },
          "players": { "type": "integer" }
        },
        "required": ["name", "quantity", "color"],
        "additionalProperties": false
      }
    },
    "upgrades": {
      "type": "object",
      "additionalProperties": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "minItems": 1,
        "uniqueItems": true
      }
    },
    "wip": { "type": "boolean" },
    "prototype": { "type": "boolean" }
  },
  "additionalProperties": false,
  "required": ["info"]
}

=== 18xx-maker/18xx-maker/src/data/games/18H8U.json
{
  "info": {
    "title": "18H8U",
    "designer": "Mark Derrick",
    "background": "pink",
    "currency": "USD"
  },
  "tokens": [
    "Round"
  ],
  "wip": true,
  "ipo": true,
  "bank": 12000,
  "players": [
    {
      "number": 3,
      "certLimit": 16,
      "capital": 501
    },
    {
      "number": 4,
      "certLimit": 12,
      "capital": 411
    },
    {
      "number": 5,
      "certLimit": 10,
      "capital": 331
    }
  ],
  "shareTypes": {
    "default": [
      {
        "quantity": 1,
        "label": "President's Certificate",
        "percent": 20,
        "shares": 2
      },
      {
        "quantity": 8,
        "percent": 10,
        "shares": 1
      }
    ]
  },
  "tokenTypes": {
    "two": [
      "Home",
      40
    ],
    "three": [
      "Home",
      40,
      100
    ],
    "four": [
      "Home",
      40,
      100,
      100
    ]
  },
  "companies": [],
  "trains": [],
  "privates": [],
  "phases": [],
  "pools": [
    {
      "name": "Market",
      "notes": [
        {
          "color": "orange",
          "note": "Shares in the market pay dividends to the corporation"
        },
        {
          "color": "brown",
          "icon": "exclamation",
          "note": "No more than 50% of a corporation's shares may be in the market at any time"
        },
        {
          "color": "red",
          "icon": "times",
          "note": "Shares cannot be sold during the first stock round"
        }
      ]
    }
  ],
  "rounds": [
    {
      "name": "OR3",
      "color": "brown"
    },
    {
      "name": "OR2",
      "color": "green"
    },
    {
      "name": "OR1",
      "color": "yellow"
    },
    {
      "name": "SR",
      "color": "white"
    }
  ],
  "turns": [
    {
      "name": "Stock Round",
      "steps": [
        "Sell any number of shares",
        "Buy one share",
        "Sell any number of shares"
      ],
      "ordered": true
    },
    {
      "name": "Operating Round",
      "steps": [
        "Lay or upgrade track",
        "Purchase a station",
        "Run trains",
        "Pay dividends or withhold revenue",
        "Purchase trains"
      ],
      "ordered": true,
      "optional": [
        "Purchase private companies"
      ]
    }
  ],
  "stock": {
    "type": "2D",
    "par": {
      "values": [
        85,
        78,
        69,
        65,
        49
      ]
    },
    "movement": {
      "up": [
        "Sold out"
      ],
      "down": [
        "Every share sold"
      ],
      "left": [
        "Revenue withheld"
      ],
      "right": [
        "Revenue paid out"
      ]
    },
    "market": [
      [
        {
          "value": 72,
          "arrow": "down"
        },
        {
          "value": 77,
          "arrow": "down"
        }
      ],
      [
        {
          "value": 63,
          "arrow": "down"
        },
        68,
        73,
        {
          "value": 78,
          "par": true
        },
        {
          "value": 83,
          "arrow": "down"
        }
      ],
      [
        {
          "value": 54,
          "arrow": "down"
        },
        59,
        64,
        {
          "value": 69,
          "par": true
        },
        74,
        {
          "value": 85,
          "par": true
        },
        95,
        {
          "value": 105,
          "arrow": "down"
        }
      ],
      [
        {
          "value": 45,
          "arrow": "down"
        },
        50,
        55,
        60,
        {
          "value": 65,
          "par": true
        },
        75,
        85,
        100,
        {
          "value": 121,
          "subLabel": "Rust 2T",
          "legend": 1
        },
        {
          "value": 142,
          "subLabel": "Rust 3T",
          "legend": 1
        },
        {
          "value": 163,
          "subLabel": "Rust 4T",
          "legend": 1
        },
        {
          "value": 194,
          "legend": 1
        },
        {
          "value": 230,
          "width": 2,
          "subLabel": "Game Over",
          "legend": 1
        },
        null
      ],
      [
        {
          "value": 34,
          "legend": 0,
          "arrow": "down"
        },
        39,
        44,
        {
          "value": 49,
          "par": true
        },
        54,
        64,
        74,
        {
          "value": 84,
          "legend": 0,
          "arrow": "up"
        }
      ],
      [
        {
          "value": 23,
          "arrow": "down",
          "legend": 0
        },
        {
          "value": 27,
          "legend": 0
        },
        {
          "value": 33,
          "legend": 0
        },
        {
          "value": 38,
          "legend": 0
        },
        {
          "value": 49,
          "arrow": "up",
          "legend": 0
        }
      ],
      [
        {
          "value": 11,
          "legend": 0
        },
        {
          "value": 15,
          "arrow": "up",
          "legend": 0
        }
      ]
    ],
    "legend": [
      {
        "color": "yellow",
        "description": "Shares of this corporation do not count toward the certificate limit",
        "icon": "certificate"
      },
      {
        "color": "red",
        "description": "Rusting events",
        "icon": "exclamation"
      }
    ]
  },
  "tiles": {},
  "map": {
    "hexes": [],
    "borders": []
  }
}

=== 18xx-maker/18xx-maker/src/data/games/1888.json
{
  "info": {
    "title": "1888",
    "designer": "Anthony Fryer",
    "background": "gray",
    "currency": "$#"
  },
  "links": {
    "bgg": "https://boardgamegeek.com/boardgame/306259/1888",
    "rules": "https://drive.google.com/file/d/1oaaEtpR5mXjLDTG_M5NJefoTpeRJbFCc/view",
    "license": "https://traxx-denver.com/games/",
    "purchase": "https://traxx-denver.com/games/"
  },
  "wip": true,
  "tokens": ["Round"],
  "ipo": true,
  "bank": 12000,
  "tiles": {
    "1": 1,
    "2": 1,
    "3": 2,
    "4": 2,
    "7": 4,
    "8": 8,
    "9": 7,
    "14": 3,
    "15": 2,
    "16": 1,
    "18": 1,
    "19": 1,
    "20": 1,
    "23": 3,
    "24": 3,
    "25": 1,
    "26": 1,
    "27": 1,
    "28": 1,
    "29": 1,
    "39": 1,
    "40": 1,
    "41": 2,
    "42": 2,
    "43": 2,
    "44": 1,
    "45": 2,
    "46": 2,
    "47": 1,
    "53": 2,
    "54": 1,
    "55": 1,
    "56": 1,
    "57": 4,
    "58": 2,
    "59": 2,
    "61": 2,
    "62": 1,
    "63": 3,
    "64": 1,
    "65": 1,
    "66": 1,
    "67": 1,
    "68": 1,
    "69": 1,
    "70": 1,
    "88|OO1": {
      "color": "gray",
      "quantity": 1,
      "track": [
        { "side": 1, "type": "straight" },
        { "side": 2, "type": "straight" },
        { "side": 3, "type": "straight" }
      ],
      "cities": [{ "size": 3, "rotation": 30 }],
      "labels": [
        {
          "label": "OO",
          "rotation": 30,
          "angle": -95,
          "percent": 0.8,
          "size": 20
        }
      ],
      "values": [
        {
          "value": 70,
          "rotation": 30,
          "angle": -150,
          "percent": 0.85
        }
      ]
    },
    "88|OO2": {
      "color": "gray",
      "quantity": 1,
      "track": [
        { "side": 2, "type": "sharp" },
        { "side": 3, "type": "gentle", "cross": "under" },
        { "side": 4, "type": "gentle", "cross": "over" },
        { "side": 6, "type": "sharp" }
      ],
      "cities": [
        {
          "size": 2,
          "angle": 90,
          "rotation": 90,
          "percent": 0.4
        },
        {
          "angle": -55,
          "percent": 0.6
        }
      ],
      "labels": [
        {
          "label": "OO",
          "rotation": 30,
          "angle": -95,
          "percent": 0.8,
          "size": 20
        }
      ],
      "values": [
        {
          "value": 70,
          "rotation": 30,
          "angle": -150,
          "percent": 0.85
        }
      ]
    },
    "88|OO3": {
      "color": "gray",
      "quantity": 1,
      "track": [
        { "side": 1, "type": "sharp" },
        { "side": 3, "type": "sharp" },
        { "side": 4, "type": "gentle", "cross": "over" },
        { "side": 5, "type": "gentle", "cross": "under" }
      ],
      "cities": [
        {
          "size": 2,
          "rotation": 30,
          "angle": 30,
          "percent": 0.4
        },
        {
          "angle": 170,
          "percent": 0.5
        }
      ],
      "labels": [
        {
          "label": "OO",
          "rotation": 30,
          "angle": -95,
          "percent": 0.8,
          "size": 20
        }
      ],
      "values": [
        {
          "value": 70,
          "rotation": 30,
          "angle": -150,
          "percent": 0.85
        }
      ]
    }
  }
}

=== 18xx-maker/18xx-maker/src/data/games/18NK.json
{
  "info": {
    "title": "18NK",
    "subtitle": "Nagaokakyo City",
    "designer": "CTDA",
    "background": "water",
    "currency": "JPY"
  },
  "wip": true,
  "links": {
    "bgg": "https://www.boardgamegeek.com/boardgame/109151/18nk",
    "rules": "https://www.boardgamegeek.com/boardgame/109151/18nk"
  },
  "tiles": {
    "5": 4,
    "6": 4,
    "7": 10,
    "8": 27,
    "9": 30,
    "14": 4,
    "15": 4,
    "16": 2,
    "17": 2,
    "18": 2,
    "19": 2,
    "20": 2,
    "23": 6,
    "24": 6,
    "25": 4,
    "26": 3,
    "27": 3,
    "28": 3,
    "29": 3,
    "30": 2,
    "31": 2,
    "39": 2,
    "40": 3,
    "41": 3,
    "42": 3,
    "43": 4,
    "44": 3,
    "45": 4,
    "46": 4,
    "47": 5,
    "57": 6,
    "63": 15,
    "70": 2,
    "619": 4,
    "624": 1,
    "625": 1,
    "626": 1,
    "627": 2,
    "628": 2,
    "629": 2,
    "X02": 3,
    "X03": 3,
    "X04": 3
  }
}

=== 18xx-maker/18xx-maker/src/data/games/18LA.json
{
  "info": {
    "title": "18 Los Angeles",
    "designer": "Tony Fryer",
    "background": "orange",
    "marketTokens": 2,
    "extraStationTokens": 3,
    "currency": "$#"
  },
  "links": {
    "bgg": "https://boardgamegeek.com/boardgame/306257/18-los-angeles",
    "rules": "https://drive.google.com/file/d/1G_fLbak96VWQ0Vfvg7-Qh2gXgv7r0BQi/view?usp=sharing",
    "license": "https://traxx-denver.com/games/",
    "purchase": "https://traxx-denver.com/games/"
  },
  "wip": true,
  "tiles": {
    "5": 3,
    "6": 4,
    "7": 5,
    "8": 16,
    "9": 16,
    "14": 4,
    "15": 5,
    "16": 2,
    "17": 1,
    "18": 1,
    "19": 2,
    "20": 2,
    "21": 1,
    "22": 1,
    "23": 4,
    "24": 4,
    "25": 2,
    "26": 1,
    "27": 1,
    "28": 1,
    "29": 1,
    "30": 1,
    "31": 1,
    "39": 1,
    "40": 1,
    "41": 2,
    "42": 2,
    "43": 2,
    "44": 1,
    "45": 2,
    "46": 2,
    "47": 2,
    "51": 2,
    "57": 4,
    "70": 1,
    "290": 1,
    "291": 1,
    "292": 1,
    "293": 1,
    "294": 2,
    "295": 2,
    "296": 1,
    "297": 2,
    "298|LA": {
      "color": "green",
      "labels": [{ "angle": 287, "percent": 0.7, "label": "LB" }],
      "values": [{ "angle": 323, "percent": 0.75, "value": 40 }],
      "cities": [
        { "angle": 60, "percent": 0.75 },
        { "angle": 120, "percent": 0.75 },
        {
          "angle": 180,
          "percent": 0.75,
          "companies": [{ "label": "PMC", "color": "white" }]
        },
        { "angle": 240, "percent": 0.75 }
      ],
      "track": [
        { "type": "sharp", "side": 1 },
        { "type": "gentle", "side": 1 },
        { "type": "straight", "side": 1 },
        { "type": "gentle", "side": 5 }
      ]
    },
    "299|LA": {
      "color": "brown",
      "labels": [{ "angle": 287, "percent": 0.7, "label": "LB" }],
      "values": [{ "angle": 323, "percent": 0.75, "value": 70 }],
      "cities": [
        { "angle": 60, "percent": 0.75 },
        { "angle": 120, "percent": 0.75 },
        {
          "angle": 180,
          "percent": 0.75,
          "companies": [{ "label": "PMC", "color": "white" }]
        },
        { "angle": 240, "percent": 0.75 }
      ],
      "track": [
        { "type": "sharp", "side": 1 },
        { "type": "gentle", "side": 1 },
        { "type": "straight", "side": 1 },
        { "type": "gentle", "side": 5 }
      ]
    },
    "300|LA": {
      "color": "gray",
      "labels": [{ "angle": 287, "percent": 0.7, "label": "LB" }],
      "values": [{ "angle": 323, "percent": 0.75, "value": 90 }],
      "cities": [
        { "angle": 60, "percent": 0.75 },
        { "angle": 120, "percent": 0.75 },
        {
          "angle": 180,
          "percent": 0.75,
          "companies": [{ "label": "PMC", "color": "white" }]
        },
        { "angle": 240, "percent": 0.75 }
      ],
      "track": [
        { "type": "sharp", "side": 1 },
        { "type": "gentle", "side": 1 },
        { "type": "straight", "side": 1 },
        { "type": "gentle", "side": 5 }
      ]
    },
    "611": 4,
    "619": 3
  }
}

=== 18xx-maker/18xx-maker/src/data/games/18GJ.json
{
  "info": {
    "title": "18 Grand Junction",
    "designer": "Anthony Fryer",
    "background": "orange",
    "currency": "$#"
  },
  "links": {
    "bgg": "https://www.boardgamegeek.com/boardgame/17405/1846-race-midwest",
    "rules": "https://s3-us-west-2.amazonaws.com/gmtwebsiteassets/1846/1846-RULES-GMT.pdf",
    "license": "https://traxx-denver.com/games/",
    "purchase": "https://traxx-denver.com/games/"
  },
  "wip": true,
  "companies": [
    {
      "name": "Denver, South Park, & Pacific Railroad",
      "abbrev": "DSPP",
      "tokens": ["Free", 80, 80, 80, 80],
      "token": {
        "width": 20,
        "rotation": -90,
        "shield": true,
        "shieldTop": "blue",
        "color": "white"
      },
      "color": "blue"
    }
  ],
  "tiles": {
    "5": 3,
    "6": 4,
    "7": 5,
    "8": 16,
    "9": 16,
    "14": 4,
    "15": 5,
    "16": 2,
    "17": 1,
    "18": 1,
    "19": 2,
    "20": 2,
    "21": 1,
    "22": 1,
    "23": 4,
    "24": 4,
    "25": 2,
    "26": 1,
    "27": 1,
    "28": 1,
    "29": 1,
    "30": 1,
    "31": 1,
    "39": 1,
    "40": 1,
    "41": 2,
    "42": 2,
    "43": 2,
    "44": 1,
    "45": 2,
    "46": 2,
    "47": 2,
    "51": 2,
    "57": 4,
    "70": 1,
    "290": 1,
    "291": 1,
    "292": 1,
    "293": 1,
    "294": 2,
    "295": 2,
    "296": 1,
    "297": 2,
    "298|GJ": {
      "quantity": 1,
      "color": "green",
      "labels": [{ "angle": 287, "percent": 0.7, "label": "GJ" }],
      "values": [{ "angle": 323, "percent": 0.75, "value": 40 }],
      "cities": [
        { "angle": 60, "percent": 0.75 },
        { "angle": 120, "percent": 0.75 },
        { "angle": 180, "percent": 0.75 },
        {
          "angle": 240,
          "percent": 0.75,
          "companies": [{ "abbrev": "DSPP", "rotation": -90 }]
        }
      ],
      "track": [
        { "type": "sharp", "side": 1 },
        { "type": "gentle", "side": 1 },
        { "type": "straight", "side": 1 },
        { "type": "gentle", "side": 5 }
      ]
    },
    "299|GJ": {
      "quantity": 1,
      "color": "brown",
      "labels": [{ "angle": 287, "percent": 0.7, "label": "GJ" }],
      "values": [{ "angle": 323, "percent": 0.75, "value": 70 }],
      "cities": [
        { "angle": 60, "percent": 0.75 },
        { "angle": 120, "percent": 0.75 },
        { "angle": 180, "percent": 0.75 },
        {
          "angle": 240,
          "percent": 0.75,
          "companies": [{ "abbrev": "DSPP", "rotation": -90 }]
        }
      ],
      "track": [
        { "type": "sharp", "side": 1 },
        { "type": "gentle", "side": 1 },
        { "type": "straight", "side": 1 },
        { "type": "gentle", "side": 5 }
      ]
    },
    "300|GJ": {
      "quantity": 1,
      "color": "gray",
      "labels": [{ "angle": 287, "percent": 0.7, "label": "GJ" }],
      "values": [{ "angle": 323, "percent": 0.75, "value": 90 }],
      "cities": [
        { "angle": 60, "percent": 0.75 },
        { "angle": 120, "percent": 0.75 },
        { "angle": 180, "percent": 0.75 },
        {
          "angle": 240,
          "percent": 0.75,
          "companies": [{ "abbrev": "DSPP", "rotation": -90 }]
        }
      ],
      "track": [
        { "type": "sharp", "side": 1 },
        { "type": "gentle", "side": 1 },
        { "type": "straight", "side": 1 },
        { "type": "gentle", "side": 5 }
      ]
    },
    "611": 4,
    "619": 3
  }
}
