=== 18xx-maker/18xx-maker/src/schemas/game.schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "$id": "https://18xx-maker.com/schemas/game.schema.json",

  "definitions": {
    "numberOrSlash": {
      "oneOf": [
        { "type": "number", "minimum": 1 },
        {
          "type": "string",
          "pattern": "^[0-9]+ ?/ ?[0-9]+( ?/ ?[0-9]+)*$"
        },
        {
          "type": "string",
          "pattern": "^∞$"
        }
      ]
    },
    "bank": {
      "oneOf": [
        { "type": "number", "minimum": 1 },
        {
          "type": "string",
          "pattern": "^∞$"
        }
      ]
    },
    "capital": {
      "oneOf": [{ "type": "number", "minimum": 0 }, { "type": "string" }]
    },
    "certLimit": { "$ref": "#/definitions/numberOrSlash" },
    "link": {
      "type": "string",
      "pattern": "(mailto|https?):.*"
    },
    "map": {
      "type": "object",
      "properties": {
        "name": { "type": "string" },
        "copy": { "type": "integer", "minimum": 0 },
        "title": { "type": "boolean", "enum": [false] },
        "remove": {
          "type": "array",
          "items": {
            "type": "string",
            "pattern": "^[A-Z]+[0-9]+$"
          }
        },
        "hexes": {
          "type": "array",
          "items": { "$ref": "tiles.schema.json#/definitions/hex" }
        },
        "roundTracker": {
          "type": "object",
          "properties": {
            "x": { "type": "number" },
            "y": { "type": "number" },
            "rotation": {
              "type": "number",
              "exclusiveMinimum": -360,
              "exclusiveMaximum": 360
            },
            "type": {
              "type": "string",
              "enum": ["row", "row-reverse", "col", "col-reverse", "round"]
            }
          },
          "additionalProperties": false
        },
        "players": {
          "type": "object",
          "properties": {
            "x": { "type": "number" },
            "y": { "type": "number" },
            "cellWidth": { "type": "number", "exclusiveMinimum": 0 }
          },
          "additionalProperties": false
        },
        "borderTexts": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "cost": { "type": "number" },
              "circle": { "type": "number" },
              "color": { "type": "string" },
              "bgColor": { "type": "string" },
              "coord": {
                "type": "string",
                "pattern": "^[A-Z]+[0-9]+(s[1-6])|(p[1-6])|(a[0-9]+p[0-9]+)|(x[0-9]+y[0-9]+)"
              }
            }
          }
        },
        "borders": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "color": { "type": "string" },
              "coords": {
                "type": "array",
                "items": {
                  "type": "string",
                  "pattern": "^[A-Z]+[0-9]+(s[1-6])|(p[1-6])|(a[0-9]+p[0-9]+)|(x[0-9]+y[0-9]+)"
                }
              }
            }
          }
        }
      },
      "required": ["hexes"],
      "additionalProperties": false
    },
    "trainItem": {
      "oneOf": [
        { "type": "string" },
        {
          "type": "object",
          "properties": {
            "on": { "type": "string" },
            "index": { "type": "integer", "minimum": 2 }
          }
        }
      ]
    },
    "trainEvent": {
      "oneOf": [
        { "$ref": "#/definitions/trainItem" },
        { "type": "array", "items": { "$ref": "#/definitions/trainItem" } }
      ]
    },
    "shares": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "quantity": { "type": "number", "minimum": 1 },
          "label": { "type": "string" },
          "cost": { "type": "number", "minimum": 0 },
          "percent": { "$ref": "#/definitions/numberOrSlash" },
          "revenue": { "$ref": "#/definitions/numberOrSlash" },
          "shares": { "$ref": "#/definitions/numberOrSlash" },
          "variant": { "type": "string" }
        },
        "required": ["quantity"]
      }
    },
    "tokens": {
      "type": "array",
      "items": {
        "oneOf": [
          { "type": "string" },
          { "type": "number" },
          { "$ref": "#/definitions/token" }
        ]
      }
    },
    "token": {
      "type": "object"
    }
  },

  "type": "object",
  "properties": {
    "info": {
      "type": "object",
      "properties": {
        "title": { "type": "string" },
        "subtitle": { "type": "string" },
        "designer": { "type": "string" },
        "background": { "type": "string" },
        "notes": { "type": "string" },
        "publisher": { "type": "string" },
        "extraTotalHeight": { "type": "number", "minimum": 1 },
        "extraTotalWidth": { "type": "number", "minimum": 1 },
        "titleX": { "type": "number" },
        "titleY": { "type": "number" },
        "titleRotate": {
          "type": "number",
          "minimum": -360,
          "maximum": 360
        },
        "titleSize": { "type": "number" },
        "subtitleSize": { "type": "number" },
        "designerSize": { "type": "number" },
        "titleFontFamily": { "type": "string" },
        "subtitleFontFamily": { "type": "string" },
        "designerFontFamily": { "type": "string" },
        "orientation": {
          "type": "string",
          "enum": ["horizontal", "vertical"]
        },
        "capitalization": {
          "type": "string",
          "description": "Full cap is the default and doesn't need to be specified.",
          "enum": ["incremental"]
        },
        "mustSellInBlocks": { "type": "boolean", "enum": [true] },
        "marketTokens": { "type": "integer", "minimum": 0 },
        "extraStationTokens": { "type": "integer", "minimum": 1 },
        "mustSellInBlocks": { "type": "boolean" },
        "capitalization": {
          "type": "string",
          "enum": ["full", "incremental"]
        },
        "currency": {
          "description": "The currency format string must contain a # character",
          "type": "string",
          "pattern": "^(.*)#(.*)$"
        }
      },
      "required": ["title"],
      "additionalProperties": false
    },
    "colors": {
      "type": "object"
    },
    "links": {
      "type": "object",
      "properties": {
        "bgg": { "$ref": "#/definitions/link" },
        "license": { "$ref": "#/definitions/link" },
        "purchase": { "$ref": "#/definitions/link" },
        "rules": { "$ref": "#/definitions/link" }
      },
      "additionalProperties": false
    },
    "bank": { "$ref": "#/definitions/bank" },
    "capital": { "$ref": "#/definitions/capital" },
    "certLimit": { "$ref": "#/definitions/certLimit" },
    "floatPercent": { "type": "number", "minimum": 0, "maximum": 100 },
    "tokenTypes": {
      "type": "object",
      "additionalProperties": { "$ref": "#/definitions/tokens" }
    },
    "shareTypes": {
      "type": "object",
      "additionalProperties": { "$ref": "#/definitions/shares" }
    },
    "companies": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["name", "abbrev"],
        "properties": {
          "name": { "type": "string" },
          "variant": { "type": "string" },
          "shares": {
            "oneOf": [{ "$ref": "#/definitions/shares" }, { "type": "string" }]
          },
          "tokens": {
            "oneOf": [{ "$ref": "#/definitions/tokens" }, { "type": "string" }]
          }
        }
      }
    },
    "ipo": {
      "oneOf": [
        { "type": "boolean" },
        { "type": "array", "items": { "type": "string" } }
      ]
    },
    "map": {
      "oneOf": [
        { "$ref": "#/definitions/map" },
        { "type": "array", "items": { "$ref": "#/definitions/map" } }
      ]
    },
    "phases": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "minor": { "type": "boolean" },
          "company": { "type": "string" },
          "train": {
            "oneOf": [
              { "type": "array", "items": { "type": "string" } },
              { "type": "string" }
            ]
          },
          "limit": {
            "oneOf": [
              { "type": "integer", "minimum": 1 },
              {
                "type": "string",
                "pattern": "^∞$"
              }
            ]
          },
          "rounds": { "type": "integer", "minimum": 1 },
          "tiles": { "type": "string" },
          "on": { "$ref": "#/definitions/trainEvent" },
          "notes": {
            "oneOf": [
              { "type": "string" },
              {
                "type": "array",
                "items": { "type": "string" }
              }
            ]
          },
          "buy_companies": { "type": "boolean" },
          "events": {
            "type": "object",
            "additionalProperties": {
              "type": "boolean"
            }
          }
        },
        "required": ["name", "limit", "tiles"],
        "additionalProperties": false
      }
    },
    "players": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "bank": { "$ref": "#/definitions/bank" },
          "capital": { "$ref": "#/definitions/capital" },
          "certLimit": { "$ref": "#/definitions/certLimit" },
          "number": { "type": "number", "minimum": 1 }
        },
        "required": ["number"]
      }
    },
    "pools": {},
    "privates": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "note": { "type": "string" },
          "minPlayers": { "type": "integer", "minimum": 1 },
          "maxPlayers": { "type": "integer", "minimum": 1 },
          "description": { "type": "string" },
          "hex": { "type": "string" },
          "token": { "$ref": "#/definitions/token" },
          "company": { "type": "string" },
          "image": { "type": "string" },
          "icon": { "type": "string" },
          "iconColor": { "type": "string" },
          "tile": { "type": "string" },
          "id": { "type": "string" },
          "idBackgroundColor": { "type": "string" },
          "variant": { "type": "string" },
          "sym": { "type": "string" },
          "abilities": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "type": { "type": "string" }
              }
            }
          },
          "bid": { "type": "number", "minimum": 0 },
          "price": { "type": "number", "minimum": 0 },
          "debt": { "type": "number", "minimum": 0 },
          "revenue": {
            "oneOf": [
              { "type": "number", "minimum": 0 },
              {
                "type": "array",
                "items": { "type": "number", "minimum": 0 }
              },
              {
                "type": "string",
                "pattern": "^.?.?[0-9].?%? ?/ ?.?.?[0-9].?%?$"
              }
            ]
          }
        },
        "required": ["name"],
        "additionalProperties": false
      }
    },
    "rounds": {},
    "stock": {},
    "tiles": {
      "type": "object",
      "additionalProperties": {
        "oneOf": [
          {
            "type": "integer",
            "minimum": 1
          },
          {
            "$ref": "tiles.schema.json#/definitions/hex"
          }
        ]
      }
    },
    "tokens": {},
    "turns": {},
    "trains": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "price": { "type": "integer", "minimum": 0 },
          "color": { "type": "string" },
          "image": {
            "type": "string"
          },
          "phase": { "type": "boolean" },
          "quantity": {
            "oneOf": [
              { "type": "integer", "minimum": 1 },
              { "type": "string", "enum": ["∞"] }
            ]
          },
          "print": { "type": "integer", "minimum": 0 },
          "discount": { "type": "object" },
          "description": { "type": "string" },
          "available": { "type": "string" },
          "variant": { "type": "string" },
          "rust": { "$ref": "#/definitions/trainEvent" },
          "phased": { "$ref": "#/definitions/trainEvent" },
          "obsolete": { "$ref": "#/definitions/trainEvent" },
          "permanent": { "type": "boolean" },
          "players": { "type": "integer" }
        },
        "required": ["name", "quantity", "color"],
        "additionalProperties": false
      }
    },
    "upgrades": {
      "type": "object",
      "additionalProperties": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "minItems": 1,
        "uniqueItems": true
      }
    },
    "wip": { "type": "boolean" },
    "prototype": { "type": "boolean" }
  },
  "additionalProperties": false,
  "required": ["info"]
}

=== 18xx-maker/18xx-maker/src/data/games/18SY.json
{
  "info": {
    "title": "18SY",
    "subtitle": "Railroading in Southern Yamaguchi",
    "designer": "Toryo Hojo",
    "background": "water",
    "currency": "Â¥#"
  },
  "wip": true,
  "links": {
    "bgg": "https://www.boardgamegeek.com/boardgame/42664/18sy",
    "rules": "https://www.boardgamegeek.com/filepage/146452/18sy-original-rules-summary"
  },
  "tiles": {
    "1": 2,
    "2": 7,
    "5": 2,
    "6": 3,
    "7": 12,
    "8": 12,
    "9": 12,
    "14": 2,
    "15": 4,
    "16": 2,
    "17": 1,
    "18": 3,
    "19": 1,
    "20": 1,
    "21": 2,
    "22": 2,
    "23": 3,
    "24": 3,
    "25": 1,
    "26": 1,
    "27": 1,
    "28": 1,
    "29": 1,
    "30": 1,
    "31": 1,
    "39": 1,
    "40": 1,
    "41": 1,
    "42": 1,
    "43": 1,
    "44": 1,
    "45": 2,
    "46": 2,
    "47": 2,
    "55": 2,
    "56": 6,
    "57": 3,
    "63": 8,
    "69": 3,
    "70": 1,
    "619": 4,
    "622": 2,
    "623": 2,
    "624": 1,
    "625": 3,
    "626": 1,
    "627": 1,
    "628": 1,
    "629": 1,
    "630": 3,
    "631": 3,
    "632": 6,
    "633": 2,
    "SY1": {
      "color": "yellow",
      "centerTowns": [
        {
          "angle": 120,
          "percent": 0.45
        },
        {
          "angle": 240,
          "percent": 0.45
        }
      ],
      "track": [
        {
          "side": 6,
          "type": "gentle"
        }
      ]
    },
    "SY2": {
      "color": "yellow",
      "values": [
        {
          "angle": 150,
          "percent": 0.6,
          "value": 10
        }
      ],
      "towns": [
        {
          "angle": 90,
          "percent": 0.57735
        }
      ],
      "centerTowns": [
        {
          "angle": 270,
          "percent": 0.2
        }
      ],
      "track": [
        {
          "side": 2,
          "type": "sharp"
        },
        {
          "side": 5,
          "type": "sharp"
        }
      ]
    },
    "SY3": {
      "color": "yellow",
      "values": [
        {
          "percent": 0.5,
          "value": 10
        },
        {
          "angle": 210,
          "percent": 0.8,
          "value": 10
        }
      ],
      "centerTowns": [
        {},
        {
          "angle": 180,
          "percent": 0.5
        }
      ],
      "track": [
        {
          "type": "custom",
          "path": "M 0 0 Q 40 -20, 0 -40"
        },
        {
          "type": "custom",
          "path": "M 0 0 Q -40 -20, 0 -40"
        },
        {
          "side": 2
        },
        {
          "side": 6
        }
      ]
    },
    "SY4": {
      "color": "yellow",
      "values": [
        {
          "value": 10,
          "angle": 90,
          "percent": 0.5
        },
        {
          "value": 10,
          "angle": 225,
          "percent": 0.7
        }
      ],
      "centerTowns": [
        {},
        {
          "angle": 270,
          "percent": 0.667
        }
      ],
      "track": [
        {
          "side": 1,
          "type": "straight"
        },
        {
          "side": 5.5,
          "type": "mid"
        }
      ]
    },
    "125|SY": {
      "color": "brown",
      "values": [
        {
          "angle": 210,
          "percent": 0.87,
          "value": 40
        }
      ],
      "cities": [
        {
          "size": 2,
          "name": {
            "name": "Asa",
            "reverse": true
          }
        }
      ],
      "track": [
        {
          "side": 2
        },
        {
          "side": 3
        },
        {
          "side": 4
        },
        {
          "side": 5
        },
        {
          "side": 6
        }
      ]
    },
    "SY5": {
      "color": "gray",
      "values": [
        {
          "angle": 210,
          "percent": 0.87,
          "value": 60
        }
      ],
      "cities": [
        {
          "size": 3,
          "name": {
            "name": "Asa",
            "offset": 4,
            "reverse": true,
            "y": 10
          }
        }
      ],
      "track": [
        {
          "side": 2
        },
        {
          "side": 3
        },
        {
          "side": 4
        },
        {
          "side": 5
        },
        {
          "side": 6
        }
      ]
    },
    "SY6": {
      "color": "gray",
      "values": [
        {
          "angle": 210,
          "percent": 0.87,
          "value": 60
        }
      ],
      "cities": [
        {
          "size": 3,
          "name": {
            "name": "Ogori",
            "offset": 25,
            "reverse": true,
            "y": 10
          }
        }
      ],
      "track": [
        {
          "side": 1
        },
        {
          "side": 2
        },
        {
          "side": 3
        },
        {
          "side": 4
        },
        {
          "side": 5
        },
        {
          "side": 6
        }
      ]
    }
  }
}

=== 18xx-maker/18xx-maker/src/data/games/1891.json
{
  "info": {
    "title": "1891",
    "subtitle": "Railroading in Hiroshima",
    "designer": "Toryo Hojo",
    "background": "water",
    "currency": "JPY"
  },
  "wip": true,
  "links": {
    "bgg": "https://www.boardgamegeek.com/boardgame/38304/1891",
    "rules": "https://www.boardgamegeek.com/filepage/142184/1891-rules"
  },
  "tiles": {
    "1": 1,
    "2": 2,
    "3": 3,
    "4": 5,
    "5": 2,
    "6": 4,
    "7": 7,
    "8": 19,
    "9": 13,
    "14": 5,
    "15": 6,
    "16": 2,
    "17": 1,
    "18": 1,
    "19": 1,
    "20": 1,
    "23": 4,
    "24": 4,
    "25": 2,
    "26": 1,
    "27": 1,
    "28": 1,
    "29": 1,
    "39": 1,
    "40": 1,
    "41": 1,
    "42": 1,
    "43": 1,
    "44": 1,
    "45": 2,
    "46": 2,
    "47": 2,
    "55": 1,
    "56": 1,
    "57": 5,
    "58": 5,
    "59": 2,
    "63": 4,
    "64": 1,
    "65": 1,
    "66": 1,
    "67": 1,
    "68": 1,
    "69": 1,
    "70": 1,
    "202": 1,
    "611": 4,
    "622": 2,
    "623": 1,
    "H902": {
      "color": "green",
      "values": [
        {
          "value": 50,
          "angle": 90,
          "percent": 0.85
        }
      ],
      "cities": [
        {
          "size": 2,
          "angle": 90,
          "percent": 0.3,
          "rotate": 90
        },
        {
          "size": 2,
          "angle": 270,
          "percent": 0.5,
          "rotate": 90
        }
      ],
      "track": [
        {
          "side": 1,
          "type": "sharpStop"
        },
        {
          "side": 4,
          "type": "sharpStopRev"
        },
        {
          "side": 5,
          "type": "stub"
        },
        {
          "side": 6,
          "type": "stub"
        }
      ]
    },
    "H908": {
      "color": "green",
      "cities": [
        {
          "size": 2,
          "name": {
            "reverse": true,
            "name": "Tomo"
          },
          "rotate": -90
        }
      ],
      "values": [
        {
          "value": 30,
          "angle": 90,
          "percent": 0.8
        }
      ],
      "track": [
        {
          "side": 2
        },
        {
          "side": 3
        }
      ]
    },
    "H901": 1,
    "H903": 1,
    "H905": 3,
    "H904": 1,
    "H906": 1,
    "H907": 1
  }
}

=== 18xx-maker/18xx-maker/src/data/games/18SS.json
{
  "info": {
    "title": "18SS",
    "designer": "CTDA",
    "background": "water",
    "currency": "JPY"
  },
  "wip": true,
  "links": {
    "bgg": "https://www.boardgamegeek.com/boardgame/109152/18ss",
    "rules": "https://www.boardgamegeek.com/filepage/146451/18ss-rules-summary"
  },
  "tiles": {
    "5": 3,
    "6": 3,
    "7": 8,
    "8": 23,
    "9": 27,
    "14": 4,
    "15": 4,
    "16": 2,
    "17": 2,
    "18": 2,
    "19": 2,
    "20": 2,
    "23": 8,
    "24": 8,
    "25": 4,
    "26": 2,
    "27": 2,
    "28": 2,
    "29": 2,
    "30": 2,
    "31": 2,
    "39": 2,
    "40": 2,
    "41": 2,
    "42": 2,
    "43": 3,
    "44": 2,
    "45": 4,
    "46": 4,
    "47": 5,
    "57": 4,
    "70": 2,
    "514": 1,
    "515": 1,
    "516": 1,
    "619": 4,
    "624": 1,
    "625": 1,
    "626": 1,
    "627": 1,
    "628": 1,
    "629": 1,
    "SS01": 1,
    "SS03": 1,
    "SS05": 1,
    "SS07": 14,
    "SS02": 1,
    "SS04": 1,
    "SS06": 1
  }
}
